# Shopify CLI Web配置文件
# 这个文件允许Shopify CLI识别和管理您的web应用

type = "frontend"

[commands]
# 开发模式命令 - 启动完整的开发环境
dev = "npm run dev"

# 构建命令  
build = "npm run build"

[commands.deploy]
# 生产部署时的构建命令
build = "npm run build"

# 开发服务器配置
[dev]
port = 5173