# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "22c17ecd1ecf677dc1c78552e650bd34"
name = "Product Importer"
handle = "amm10090-product-importer-v2"
application_url = "https://shopify.amoze.cc"
embedded = true
include_config_on_deploy = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "amm10090.myshopify.com"
include_config_on_deploy = true

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/api/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "/api/webhooks/orders/create"

  [[webhooks.subscriptions]]
  topics = [ "products/update" ]
  uri = "/api/webhooks/products/update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_inventory,read_orders,read_product_listings,read_products,write_inventory,write_product_listings,write_products"

[auth]
redirect_urls = [
  "https://shopify.amoze.cc/auth/callback",
  "https://shopify.amoze.cc/auth/shopify/callback",
  "https://shopify.amoze.cc/api/auth/callback"
]
[app_proxy]
url = "https://shopify.amoze.cc/apps/amm10090-product-importer-v2"
subpath = "proxy"
prefix = "apps"

[pos]
embedded = false
