# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Product Importer"
client_id = "22c17ecd1ecf677dc1c78552e650bd34"
handle = "product-importer-66"
include_config_on_deploy = true
application_url = "https://boston-lisa-confidence-wed.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "amm10090.myshopify.com"
include_config_on_deploy = true
web_directories = [ "." ]

  [build.include]
  "*" = "dist/**/*"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_inventory,write_inventory,read_product_listings,write_product_listings,read_orders"

[auth]
redirect_urls = [
  "https://boston-lisa-confidence-wed.trycloudflare.com/auth/callback",
  "https://boston-lisa-confidence-wed.trycloudflare.com/auth/shopify/callback",
  "https://boston-lisa-confidence-wed.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/api/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "/api/webhooks/orders/create"

  [[webhooks.subscriptions]]
  topics = [ "products/update" ]
  uri = "/api/webhooks/products/update"

[pos]
embedded = false

[app_proxy]
url = "https://boston-lisa-confidence-wed.trycloudflare.com:8443/apps/product-importer"
subpath = "proxy"
prefix = "apps"
